=== pvdung/opensftp/branches/opensftp/0.2/src/opensftp-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://opensftp.sf.net/opensftp-config"
	elementFormDefault="qualified">
	<element name="opensftp-config">
		<complexType>
			<all>
				<element name="sftputil-impl" minOccurs="0">
					<complexType>
						<sequence maxOccurs="unbounded" minOccurs="0">
							<choice>
								<element name="property">
									<complexType>
										<attribute name="name" type="string" use="required" />
										<attribute name="type" type="string" use="required" />
										<attribute name="value" type="string" use="required" />
									</complexType>
								</element>
								<element name="property-ref">
									<complexType>
										<attribute name="name" type="string" use="required" />
										<attribute name="type" type="string" use="required" />
										<attribute name="ref" type="string" use="required" />
									</complexType>
								</element>
							</choice>
						</sequence>
						<attribute name="type" type="string" use="required" />
					</complexType>
				</element>
				<element name="interceptors" minOccurs="0">
					<complexType>
						<sequence maxOccurs="unbounded" minOccurs="0">
							<element name="interceptor">
								<complexType>
									<sequence maxOccurs="unbounded" minOccurs="0">
										<choice>
											<element name="property">
												<complexType>
													<attribute name="name" type="string" use="required" />
													<attribute name="type" type="string" use="required" />
													<attribute name="value" type="string" use="required" />
												</complexType>
											</element>
											<element name="property-ref">
												<complexType>
													<attribute name="name" type="string" use="required" />
													<attribute name="type" type="string" use="required" />
													<attribute name="ref" type="string" use="required" />
												</complexType>
											</element>
										</choice>
									</sequence>
									<attribute name="name" type="ID" use="required" />
									<attribute name="type" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

				<element name="beans" minOccurs="0">
					<complexType>
						<sequence maxOccurs="unbounded" minOccurs="0">
							<element name="bean">
								<complexType>
									<sequence>
										<sequence maxOccurs="unbounded" minOccurs="0">
											<choice>
												<element name="property">
													<complexType>
														<attribute name="name" type="string" use="required" />
														<attribute name="type" type="string" use="required" />
														<attribute name="value" type="string" use="required" />
													</complexType>
												</element>
												<element name="property-ref">
													<complexType>
														<attribute name="name" type="string" use="required" />
														<attribute name="type" type="string" use="required" />
														<attribute name="ref" type="string" use="required" />
													</complexType>
												</element>
											</choice>
										</sequence>
										<element name="initializing-block" type="string"
											maxOccurs="1" minOccurs="0" />
									</sequence>
									<attribute name="name" type="ID" use="required" />
									<attribute name="type" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>

			</all>
		</complexType>
	</element>
</schema>

=== pvdung/opensftp/branches/opensftp/test/opensftp-config-testsuite4.xml
<?xml version="1.0" encoding="UTF-8"?>
<opensftp-config xmlns="http://opensftp.sf.net/opensftp-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opensftp.sf.net/opensftp-config opensftp-config.xsd ">
	<sftputil-impl type="net.sf.opensftp.impl.SftpUtil">
		<property-ref name="prompter" type="net.sf.opensftp.impl.SwingPrompter"
			ref="swingPrompter" />
	</sftputil-impl>
	<interceptors>
		<interceptor name="loggingInterceptor"
			type="net.sf.opensftp.interceptor.LoggingInterceptor" />
		<interceptor name="dummyInterceptor"
			type="net.sf.opensftp.interceptor.DummyInterceptor">
			<property name="dummyfield1" type="java.lang.String" value="value1" />
			<property name="dummyfield2" type="java.lang.Integer" value="2" />
			<property-ref name="dummyfield3" type="java.util.HashMap"
				ref="dummyMap" />
			<property-ref name="dummyfield4" type="java.util.Date"
				ref="dummyDate" />
			<property-ref name="dummyfield5" type="java.text.DateFormat"
				ref="dummyDateFormat" />
		</interceptor>
	</interceptors>
	<beans>
		<bean name="swingPrompter" type="net.sf.opensftp.impl.SwingPrompter" />
		<bean name="dummyMap" type="java.util.HashMap">
			<initializing-block>put("1","one");put("2","two");put("5","five");</initializing-block>
		</bean>
		<bean name="dummyDate" type="java.util.Date">
			<property name="hours" type="java.lang.Integer" value="17" />
			<property name="minutes" type="java.lang.Integer" value="30" />
			<initializing-block>setSeconds(40);</initializing-block>
		</bean>
		<bean name="dummyDateFormat" type="java.text.SimpleDateFormat">
			<property-ref name="calendar" type="java.util.Calendar"
				ref="dummyCalendar" />
		</bean>
		<bean name="dummyCalendar" type="java.util.GregorianCalendar">
			<property-ref name="time" type="java.util.Date" ref="dummyDate2" />
		</bean>
		<bean name="dummyDate2" type="java.util.Date" />
	</beans>
</opensftp-config>

=== pvdung/opensftp/branches/opensftp-impl/test/opensftp-config-testcases.xml
<?xml version="1.0" encoding="UTF-8"?>
<opensftp-config xmlns="http://opensftp.sf.net/opensftp-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opensftp.sf.net/opensftp-config opensftp-config.xsd ">
	<sftputil-impl>sftputil-impl</sftputil-impl>
	<interceptors>
		<interceptor type="net.sf.opensftp.LoggingInterceptor" />
		<interceptor type="net.sf.opensftp.MonitoringInterceptor" />

		<interceptor type="net.sf.opensftp.DummyInterceptor">
			<property name="dummyfield1" type="string" value="value1" />
			<property name="dummyfield2" type="int" value="2" />
			<property-ref name="dummyfield3" type="java.util.HashMap"
				ref="dummyMap" />
			<property-ref name="dummyfield4" type="java.util.Date"
				ref="dummyDate" />
			<property-ref name="dummyfield5" type="java.text.DateFormat"
				ref="dummyDateFormat" />
		</interceptor>
	</interceptors>
	<beans>
		<bean name="dummyMap" type="java.util.HashMap">
			<initializing-block>put(1,"one");put(2,"two");put(5,"five");</initializing-block>
		</bean>
		<bean name="dummyDate" type="java.util.Date">
			<property name="hours" type="int" value="17" />
			<property name="minutes" type="int" value="30" />
			<initializing-block>setSeconds(40);</initializing-block>
		</bean>
		<bean name="dummyDateFormat" type="java.text.DateFormat">
			<property-ref name="calendar" type="java.util.Calendar"
				ref="dummyCalendar" />
		</bean>
		<bean name="dummyCalendar" type="java.util.Calendar">
			<property-ref name="time" type="java.util.Date" ref="dummyDate2" />
		</bean>
		<bean name="dummyDate2" type="java.util.Date" />
	</beans>
</opensftp-config>

=== pvdung/opensftp/branches/opensftp/0.3/test/opensftp-config-6.xml
<?xml version="1.0" encoding="UTF-8"?>
<opensftp-config xmlns="http://opensftp.sf.net/opensftp-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opensftp.sf.net/opensftp-config opensftp-config.xsd ">
	<sftputil-impl type="net.sf.opensftp.impl.SftpUtil">
		<property-ref name="prompter" type="net.sf.opensftp.prompter.Prompter"
			ref="swingPrompter" />
		<property-ref name="progressListener" type="net.sf.opensftp.ProgressListener"
			ref="plainProgressListener" />
	</sftputil-impl>
	<interceptors>
		<interceptor name="loggingInterceptor"
			type="net.sf.opensftp.interceptor.LoggingInterceptor">
			<property name="logCommand" type="java.lang.Boolean" value="true" />
		</interceptor>
	</interceptors>
	<beans>
		<bean name="swingPrompter" type="net.sf.opensftp.prompter.SwingPrompter" />
		<bean name="plainProgressListener" type="net.sf.opensftp.impl.PlainProgressListener" />
	</beans>
</opensftp-config>

=== pvdung/opensftp/branches/opensftp-impl/test/opensftp-config-testsuite5.xml
<?xml version="1.0" encoding="UTF-8"?>
<opensftp-config xmlns="http://opensftp.sf.net/opensftp-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://opensftp.sf.net/opensftp-config opensftp-config.xsd ">
	<sftputil-impl type="net.sf.opensftp.impl.SftpUtil">
		<property-ref name="prompter" type="net.sf.opensftp.impl.SwingPrompter"
			ref="swingPrompter" />
	</sftputil-impl>
	<interceptors>
		<interceptor name="loggingInterceptor"
			type="net.sf.opensftp.interceptor.LoggingInterceptor">
			<property name="logCommand" type="java.lang.Boolean" value="true" />
		</interceptor>
	</interceptors>
	<beans>
		<bean name="swingPrompter" type="net.sf.opensftp.impl.SwingPrompter" />
	</beans>
</opensftp-config>
